# Experiment 12
### Name: Tannishtha Gupta
### PRN: 25070123049
### Class: Entc A3
### Title: Data Preprocessing and Handling Missing Values in Python

In [1]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'C1': [11,21, np.nan],'C2': [15, np.nan, np.nan], 'C3': [10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [2]:
df1.isna()

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [3]:
df1.notna()

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [4]:
df1.isna().sum()

C1    1
C2    2
C3    0
dtype: int64

In [5]:
df1.dropna()

     C1    C2  C3
0  11.0  15.0  10

In [6]:
df1.fillna(value= 'DEFAULT')

        C1       C2  C3
0     11.0     15.0  10
1     21.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [7]:
df1.fillna(df1.mean()) # mean values of the columns are calculated

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [16]:
#Preprocessing on a Dataset-1
import pandas as pd

data1 = {
    "Roll No": [101, 102, 103, 104, 105],
    "Name": ["Tanmay", "Tannishtha", "Kiara", "Adya", "Kashish"],
    "Age": [20, "-", 21, 20, "22"],
    "Marks": [85, 90, "-", 88, 76],
    "Department": ["CSE", "IT", "ENTC", "cse", "CSE"],
    "Admission date": ["01-06-2023"," 03-06-2023", "05-06-2023" , "07-04-2023" , "12-04-2023"]
}
df2 = pd.DataFrame(data1)
df2.to_csv("student_data.csv" , index= False)

In [19]:
import pandas as pd
import numpy as np
df = pd.read_csv("student_data.csv")
print("Original data:")
print(df)

Original data:
   Roll No        Name Age Marks Department Admission date
0      101      Tanmay  20    85        CSE     01-06-2023
1      102  Tannishtha   -    90         IT     03-06-2023
2      103       Kiara  21     -       ENTC     05-06-2023
3      104        Adya  20    88        cse     07-04-2023
4      105     Kashish  22    76        CSE     12-04-2023

In [20]:
df.replace("-", np.nan , inplace= True)
df

   Roll No        Name  Age Marks Department Admission date
0      101      Tanmay   20    85        CSE     01-06-2023
1      102  Tannishtha  NaN    90         IT     03-06-2023
2      103       Kiara   21   NaN       ENTC     05-06-2023
3      104        Adya   20    88        cse     07-04-2023
4      105     Kashish   22    76        CSE     12-04-2023

In [23]:
#step 2- replace the - with NaN to mark missing values
df.replace("-", np.nan, inplace= True)
df["Age"] = pd.to_numeric(df["Age"], errors= "coerce")
df["Marks"] = pd.to_numeric(df["Marks"], errors= "coerce")
''' When converting data (like strings -> datetime),
if some values are invalid or cannot be converted,
instead of throwing and error, it will:
Replace those invalid values with NaT (Not a Time)'''

df

   Roll No        Name   Age  Marks Department Admission date
0      101      Tanmay  20.0   85.0        CSE     01-06-2023
1      102  Tannishtha   NaN   90.0         IT     03-06-2023
2      103       Kiara  21.0    NaN       ENTC     05-06-2023
3      104        Adya  20.0   88.0        cse     07-04-2023
4      105     Kashish  22.0   76.0        CSE     12-04-2023

In [24]:
# step 3, check missing values
print("\nMissing values:")
print(df.isnull().sum())

Missing values:
Roll No           0
Name              0
Age               1
Marks             1
Department        0
Admission date    0
dtype: int64

In [25]:
# fill missing age with mean
mean_age = df["Age"].mean()
df["Age"].fillna(mean_age, inplace= True)

/tmp/ipykernel_6215/2889171519.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(mean_age, inplace= True)

In [26]:
# fill missing marks with median
median_marks = df["Marks"].median()
df["Marks"].fillna(median_marks, inplace= True)

/tmp/ipykernel_6215/36472235.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(median_marks, inplace= True)

In [27]:
df

   Roll No        Name    Age  Marks Department Admission date
0      101      Tanmay  20.00   85.0        CSE     01-06-2023
1      102  Tannishtha  20.75   90.0         IT     03-06-2023
2      103       Kiara  21.00   86.5       ENTC     05-06-2023
3      104        Adya  20.00   88.0        cse     07-04-2023
4      105     Kashish  22.00   76.0        CSE     12-04-2023

In [29]:
print(df.isnull(  ).sum())

Roll No           0
Name              0
Age               0
Marks             0
Department        0
Admission date    0
dtype: int64

In [31]:
#step 5: fix inconsistent text formatting
df["Department"] = df["Department"].str.upper

In [34]:
#step 6: convert admission date to standard date time format
df["Admission date"]  = pd.to_datetime(df["Admission date"] , errors = "coerce")

In [35]:
# step 7: show cleaned data
print("\nCleaned data:")
print(df)

Cleaned data:
   Roll No        Name    Age  Marks  \
0      101      Tanmay  20.00   85.0
1      102  Tannishtha  20.75   90.0
2      103       Kiara  21.00   86.5
3      104        Adya  20.00   88.0
4      105     Kashish  22.00   76.0

                                          Department Admission date
0  <bound method StringMethods.upper of <pandas.c...     2023-01-06
1  <bound method StringMethods.upper of <pandas.c...            NaT
2  <bound method StringMethods.upper of <pandas.c...     2023-05-06
3  <bound method StringMethods.upper of <pandas.c...     2023-07-04
4  <bound method StringMethods.upper of <pandas.c...     2023-12-04

In [36]:
#step 8 : save cleaned dataset
df.to_csv("cleaned_student_data.csv", index= False)
print("\nCleaned csv file saved as cleaned_student_data.csv")

Cleaned csv file saved as cleaned_student_data.csv

In [38]:
# working with missing values on dataset-2
df= pd.read_csv("Cars93.csv")
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [39]:
# working with missing values on dataset- 2
df= pd.read_csv("Cars93.csv")
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [45]:
#Inputing the Missing Value

#1. Luggage Room
df ['Luggage.room'] =df ['Luggage.room'].fillna(value=df ['Luggage.room'].mean())

In [42]:
#2. Rear.seat.room
df ['Rear.seat.room'] =df ['Rear.seat.room'].fillna(value=df ['Rear.seat.room'].mean())

In [44]:
#2. AirBags
df ['AirBags'] =df ['AirBags'].fillna(value=df ['AirBags'].mode().values[0])

In [46]:
# Saved cleaned dataset
df.to_csv("Cleaned_Cars93.csv", index=False)